version: '3.4'

services:
  web_service:
    build: ./
    ports:
      - 8080:80
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: org_details_db
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Passw0rd@123