apiVersion: v1
kind: Service
metadata:
  name: orgdetails-database-service
spec:
  selector:
    app: orgdetails-database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP