// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrgDetails;

#nullable disable

namespace OrgDetails.Migrations
{
    [DbContext(typeof(OrgDetailsContext))]
    partial class OrgDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrgDetails.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "steve.william@dummy.com",
                            FirstName = "Steve",
                            LastName = "William"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mark.taylor@dummy.com",
                            FirstName = "Mark",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "nick.jonas@dummy.com",
                            FirstName = "Nick",
                            LastName = "Jonas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
